### ISSUE TITLE
overly restrictive types on 'sendfile'

### ISSUE THREAD

**Issue by hasufell** [kazu-yamamoto/simple-sendfile#19]
```hs
sendfile :: Socket -> FilePath -> FileRange -> IO () -> IO ()
```

The linux manpage of `sendfile` says:
>       In  Linux kernels before 2.6.33, out_fd must refer to a socket.  Since
>       Linux 2.6.33 it can be any file.  If it is a regular file, then  send‐
>       file() changes the file offset appropriately.

This means that `sendfile` is a very fast alternative to using `read`/`write` for regular files. On platforms where this is supported, there should be version of `sendfile` that allows this.

**Comment by kazu-yamamoto** [comment]
It would be good to add a new API for regular files. However, I have no time to do it by myself. So, if you volunteer, please send me a pull request.
